[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sfn_fo_exp_date = "ERXrCZBaHPRgzTwHE71TJUh6zGCqPqQyRHL8xJgK59z4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
